#! /bin/bash

# This script is for my own use.  Don't do it.

CONFIG="$(pwd)"

# applications
ln -fsT "${CONFIG}/applications" "${HOME}/.config/applications"

# beets
ln -fsT "${CONFIG}/beets/config.yaml" "${HOME}/.config/beets/config.yaml"

# bin
ln -fsT "${CONFIG}/bin" "${HOME}/bin"

# bspwm
ln -fsT "${CONFIG}/bspwm/bspwmrc" "${HOME}/.config/bspwm/bspwmrc"

# compton
ln -fsT "${CONFIG}/compton/compton.conf" "${HOME}/.config/compton.conf"

# dunst
ln -fsT "${CONFIG}/dunst/dunstrc" "${HOME}/.config/dunst/dunstrc"

# fortune
ln -fsT "${CONFIG}/fortune" "${HOME}/.config/fortune"

# git
ln -fsT "${CONFIG}/git/gitconfig" "${HOME}/.gitconfig"

# gqrx
ln -fsT "${CONFIG}/gqrx/bookmarks.csv" "${HOME}/.config/gqrx/bookmarks.csv"

# khal
ln -fsT "${CONFIG}/khal/config" "${HOME}/.config/khal/config"

# khard
ln -fsT "${CONFIG}/khard/khard.conf" "${HOME}/.config/khard/khard.conf"

# kitty
ln -fsT "${CONFIG}/kitty/diff.conf" "${HOME}/.config/kitty/diff.conf"
ln -fsT "${CONFIG}/kitty/kitty.conf" "${HOME}/.config/kitty/kitty.conf"

# libinput
ln -fsT "${CONFIG}/libinput/libinput-gestures.conf" "${HOME}/.config/libinput-gestures.conf"

# mpv
ln -fsT "${CONFIG}/mpv/mpv.conf" "${HOME}/.config/mpv/mpv.conf"

# mutt
ln -fsT "${CONFIG}/mutt/mailcap" "${HOME}/.config/mutt/mailcap"
ln -fsT "${CONFIG}/mutt/muttrc" "${HOME}/.config/mutt/muttrc"

# ncmpcpp
ln -fsT "${CONFIG}/ncmpcpp/config" "${HOME}/.config/ncmpcpp/config"

# newsboat
ln -fsT "${CONFIG}/newsboat/config" "${HOME}/.config/newsboat/config"
ln -fsT "${CONFIG}/newsboat/urls" "${HOME}/.config/newsboat/urls"

# notmuch
ln -fsT "${CONFIG}/notmuch/notmuch-config" "${HOME}/.notmuch-config"

# nvim
ln -fsT "${CONFIG}/nvim/init.vim" "${HOME}/.config/nvim/init.vim"

# polybar
ln -fsT "${CONFIG}/polybar/config" "${HOME}/.config/polybar/config"

# ranger
ln -fsT "${CONFIG}/ranger/colorschemes/gruvbox.py" "${HOME}/.config/ranger/colorschemes/gruvbox.py"
ln -fsT "${CONFIG}/ranger/rc.conf" "${HOME}/.config/ranger/rc.conf"
ln -fsT "${CONFIG}/ranger/rifle.conf" "${HOME}/.config/ranger/rifle.conf"
ln -fsT "${CONFIG}/ranger/scope.sh" "${HOME}/.config/ranger/scope.sh"

# rofi
ln -fsT "${CONFIG}/rofi/config.rasi" "${HOME}/.config/rofi/config.rasi"
ln -fsT "${CONFIG}/rofi/gruvbox.rasi" "${HOME}/.config/rofi/gruvbox.rasi"

# sxhkd
ln -fsT "${CONFIG}/sxhkd/sxhkdrc" "${HOME}/.config/sxhkd/sxhkdrc"

# tmux
ln -fsT "${CONFIG}/tmux/tmux.conf" "${HOME}/.tmux.conf"

# wallpaper
ln -fsT "${CONFIG}/wallpaper" "${HOME}/.config/wallpaper"

# x11
ln -fsT "${CONFIG}/x11/xinitrc" "${HOME}/.xinitrc"
ln -fsT "${CONFIG}/x11/xmodmap" "${HOME}/.Xmodmap"
ln -fsT "${CONFIG}/x11/Xresources" "${HOME}/.Xresources"

# zathura
ln -fsT "${CONFIG}/zathura/zathurarc" "${HOME}/.config/zathura/zathurarc"

# zsh
ln -fsT "${CONFIG}/zsh/zshenv" "${HOME}/.zshenv"
ln -fsT "${CONFIG}/zsh/zshrc" "${HOME}/.zshrc"
ln -fsT "${CONFIG}/zsh/zprofile" "${HOME}/.zprofile"
