# {{{ display
# set background
~/.fehbg &

# compositor daemon
compton &

# notification daemon
dunst &

# disable display power management
xset -dpms &
xset s off &

# load xresources
[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources
# }}}

# {{{ keyboard and mouse
# unix style control key (swap caps lock for control)
xmodmap .Xmodmap &

# configure touchpad (sarang)
xinput --set-prop 'ETPS/2 Elantech Touchpad' "libinput Tapping Enabled" 1 &
xinput --set-prop 'ETPS/2 Elantech Touchpad' "libinput Natural Scrolling Enabled" 1 &
xinput --set-prop 'ETPS/2 Elantech Touchpad' "libinput Accel Speed" 0.4 &

# configure touchpad (kodama)
xinput --set-prop 'Asus TouchPad' "libinput Tapping Enabled" 1 &
xinput --set-prop 'Asus TouchPad' "libinput Natural Scrolling Enabled" 1 &
xinput --set-prop 'Asus Touchpad' "libinput Accel Speed" 0.4 &

# cursor hiding daemon
unclutter &
# }}}

# {{{ input daemons
# hotkeys
sxhkd &

# touchpad gestures
libinput-gestures &

# Japanese input
# export GTK_IM_MODULE='fcitx'
# export QT_IM_MODULE='fcitx'
# export XMODIFIERS='@im=fcitx'
# fcitx &
# }}}

# bell
pactl upload-sample /usr/share/sounds/freedesktop/stereo/bell.oga x11-bell &
pactl load-module module-x11-bell sample=x11-bell display=$DISPLAY &

# use the capslock led for network activity
sudo diodes &

# device mounting
devmon --sync --exec-on-drive "notify-send --icon=media-removable \"Volume mounted\" \"%l on %d\"" --exec-on-drive "urxvtc -e ranger %d" --exec-on-disc "notify-send --icon=media-optical \"Volume mounted\" \"%l on %d\"" --exec-on-disc "urxvtc -e ranger %d" &

# keyring
dbus-update-activation-environment --systemd DISPLAY &
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh) &
export SSH_AUTH_SOCK &

# welcome message
notify-send -i /usr/share/icons/Paper/48x48@2x/places/archlinux.png "welcome, ${USER}" "$(fortune ${HOME}/.config/haikus)" &

exec bspwm
