#! /bin/sh

# hotkey daemon
sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width            6
bspc config window_gap              10

bspc config split_ratio             0.5
bspc config borderless_monocle      false
bspc config gapless_monocle         false
bspc config focus_follows_pointer   true

bspc config normal_border_color     "#3c3836"
bspc config focused_border_color    "#665c54"
bspc config presel_feedback_color   "#7c6f64"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Screenkey manage=off
bspc rule -a Hamster desktop='^1'

if [[ $(hostname) == 'kodama' ]]; then
    polybar kodama &
elif [[ $(hostname) == 'sarang' ]]; then
    polybar sarang &
fi
