# {{{ general
export BROWSER=w3m
export DEFAULT_USER=oda
export EDITOR=nvim
export LANG=en_US.UTF-8
# }}}

# {{{ docker
export DOCKER_HOST="tcp://dockmaster.tiuxo.com:2376"
export DOCKER_TLS_VERIFY=1
# }}}

# {{{ gtk
export GDK_DPI_SCALE=1.5
# }}}

# {{{ java
# fix java glitches in bspwm
export _JAVA_AWT_WM_NONREPARENTING=1
export _JAVA_OPTIONS='-Dsun.java2d.opengl=true'
# }}}

# {{{ less
export LESS="-giMnRSX#3~"
export LESSOPEN="| pygmentize -g -f terminal256 -P style=abap %s"
export LESS_TERMCAP_mb=$'\e[0;31m'      # start blink escape sequence
export LESS_TERMCAP_md=$'\e[0;34m'      # start bold escape sequence
export LESS_TERMCAP_me=$'\e[0m'         # end bold, blink, and underline
export LESS_TERMCAP_se=$'\e[0m'         # stop standout escape sequence
export LESS_TERMCAP_so=$'\e[0;34;36m'   # start standout escape sequence
export LESS_TERMCAP_ue=$'\e[0m'         # stop underline escape sequence
export LESS_TERMCAP_us=$'\e[0;35m'      # start underline escape sequence
# }}}

# {{{ makeflags
export MAKEFLAGS="$MAKEFLAGS -j$(($(nproc)))"   # use all vcpus when compiling
# }}}

# {{{ path
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

if [ -d "$HOME/go/bin" ] ; then
    PATH="$HOME/go/bin:$PATH"
fi
# }}}

# {{{ qt
# use gtk styles where possible
export QT_QPA_PLATFORMTHEME=gtk2
export QT_STYLE_OVERRIDE=GTK+
# }}}

# {{{ xdg
export XDG_CONFIG_HOME=~/.config
export XDG_DATA_HOME=~/.config
# }}}

# {{{ zsh
export COLUMNS                  # remember columns for subprocesses
export skip_global_compinit=1   # compinit handled in zshrc
# }}}
